image: Visual Studio 2019  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (запоминаем информацию о процессе в переменной $App)
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-order.jar" -PassThru

build_script:
  - ps: chmod +x ./gradlew  # флаг chmod +x делает файл исполняемым
  - ps: ./gradlew test --info "-Dselenium.headless=true"  # стартуем Selenium в Headless-режиме (см.ниже)

on_finish:
  - ps: Stop-Process -Id $App.Id  # останавливаем SUT